/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Panels;

import java.awt.Image;
import Domain.Product;
import Database.SQLProductService;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author sketc
 */
public class EditProduct extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
	private Product p;
	
    public EditProduct() {
        initComponents();
    }
    public EditProduct(Product p) {
    	this.p = p;
    	initComponents();
    	SpinnerNumberModel snm = new SpinnerNumberModel();
    	snm.setMinimum(0);
    	snm.setValue(p.getInfo().getStock());
    	stock.setModel(snm);
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JButton();
        backButtom = new javax.swing.JButton();
        nameProduct = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        addStockButtom = new javax.swing.JButton();
        stock = new javax.swing.JSpinner();
        saveProduct = new javax.swing.JButton();
        deleteProductButtom = new javax.swing.JButton();
        price = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Product");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 212, 171));

        image.setBackground(new java.awt.Color(255, 111, 156));
	    
	if(p.getInfo().getImg_path()!=null && !p.getInfo().getImg_path().equals("")) {
        	image.setIcon(resizeImageIcon(new javax.swing.ImageIcon(getClass().getResource(p.getInfo().getImg_path()))));
        }
        image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editImage(evt);
            }
        });

        backButtom.setBackground(new java.awt.Color(255, 212, 171));
        backButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        backButtom.setBorder(null);
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back(evt);
            }
        });

        nameProduct.setBackground(new java.awt.Color(255, 174, 167));
        nameProduct.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nameProduct.setText(p.getInfo().getName());//nameProduct si p es null, no corre la ventana

        description.setBackground(new java.awt.Color(255, 174, 167));
        description.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        description.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        description.setText(p.getInfo().getDescription());//description si p es null, no corre la ventana

        addStockButtom.setBackground(new java.awt.Color(228, 0, 180));
        addStockButtom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addStockButtom.setText("Agregar Stock");
        addStockButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStock(evt);
            }
        });

        saveProduct.setBackground(new java.awt.Color(228, 0, 180));
        saveProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveProduct.setText("Guardar");
        saveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save(evt);
            }
        });

        deleteProductButtom.setBackground(new java.awt.Color(228, 0, 180));
        deleteProductButtom.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        deleteProductButtom.setText("Eliminar Producto");
        deleteProductButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveProduct(evt);
            }
        });

        price.setBackground(new java.awt.Color(255, 174, 167));
        price.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        price.setText(p.getInfo().getPrice()+"");//si p es null, no corre la ventana

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(price))
                        .addGap(190, 190, 190)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteProductButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addStockButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(saveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(description))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addStockButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProductButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void editImage(java.awt.event.ActionEvent evt) {                           
        // TODO add your handling code here:
    	JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
		jfc.setDialogTitle("Seleccione una imagen");
		jfc.setAcceptAllFileFilterUsed(false);
		FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG o JPEG", "png", "jpeg", "gif");
		jfc.addChoosableFileFilter(filter);
		int returnValue = jfc.showOpenDialog(null);
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			// System.out.println(jfc.getSelectedFile().getPath());
			ImageIcon userIcon = resizeImageIcon(new ImageIcon(jfc.getSelectedFile().getPath()));
			image.setIcon(userIcon);
			image.repaint();
		}
    } 
    
    private ImageIcon resizeImageIcon(ImageIcon imageIcon) {
    	Image img = imageIcon.getImage();
		img = img.getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(img);
	}

    private void AddStock(java.awt.event.ActionEvent evt) {                          
        // TODO add your handling code here:
    	int st = Integer.parseInt(stock.getValue().toString());
    	p.getInfo().setStock(st);
    }                         

    private void Save(java.awt.event.ActionEvent evt) {                      
        // TODO add your handling code here:
    	SQLProductService.getSQLProductService().update(p);
    }                     

    private void RemoveProduct(java.awt.event.ActionEvent evt) {                               
        // TODO add your handling code here:
    	SQLProductService.getSQLProductService().delete(p);
    	
    }                              

    private void Back(java.awt.event.ActionEvent evt) {                      
        // TODO add your handling code here:
    	dispose();
    	MenuAdminEdit mae = new MenuAdminEdit();
    	mae.setVisible(true);
    }                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
	    
	ProductInfo pi = new ProductInfo( "name", 0,  "description",  5,  "limpieza", "/ProductIcons/cellphone.png");
    	Product p = new Product( pi,  1, null, 0);
	    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addStockButtom;
    private javax.swing.JButton backButtom;
    private javax.swing.JButton deleteProductButtom;
    private javax.swing.JTextField description;
    private javax.swing.JButton image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameProduct;
    private javax.swing.JTextField price;
    private javax.swing.JButton saveProduct;
    private javax.swing.JSpinner stock;
    // End of variables declaration                   
}
