package Panels;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;

import Assets.ArrayToString;
import Database.SQLCategoryService;
import Domain.Client;
import Domain.Product;
import Logic.SystemService;
public class MenuAdminEdit extends javax.swing.JFrame {

    public MenuAdminEdit() {

    	categoriesList = SystemService.getSystem().getCategorys();
        
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        editUserField = new javax.swing.JTextField();
        editUserButton = new javax.swing.JButton();
        addCategoryField = new javax.swing.JTextField();
        addCategoryButton = new javax.swing.JButton();
        deleteCategoryButton = new javax.swing.JButton();
        addProductComboBox = new javax.swing.JComboBox<>();
        addProductButton = new javax.swing.JButton();
        editProductField = new javax.swing.JTextField();
        editProductButton = new javax.swing.JButton();
        editCategoryComboBox = new javax.swing.JComboBox<>();
        deleteCategoryComboBox = new javax.swing.JComboBox<>();
        editCategoryButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        showProductListButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ecommerce - Men� de Administrador");
        setBackground(new java.awt.Color(255, 212, 171));
        setBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 212, 171));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        backButton.setBackground(new java.awt.Color(255, 212, 171));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setFocusPainted(false);
        backButton.setFocusable(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 212, 171));

        editUserField.setBackground(new java.awt.Color(255, 255, 255));
        editUserField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editUserField.setForeground(new java.awt.Color(0, 0, 0));
        editUserField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        editUserField.setText("editUserField");
        editUserField.setCaretColor(new java.awt.Color(0, 0, 0));

        editUserButton.setBackground(new java.awt.Color(255, 174, 167));
        editUserButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editUserButton.setForeground(new java.awt.Color(0, 0, 0));
        editUserButton.setText("Administrar usuarios");
        editUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editUserButton.setFocusPainted(false);
        editUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        addCategoryField.setBackground(new java.awt.Color(255, 255, 255));
        addCategoryField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addCategoryField.setForeground(new java.awt.Color(0, 0, 0));
        addCategoryField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addCategoryField.setText("addCategoryField");
        addCategoryField.setAutoscrolls(false);
        addCategoryField.setCaretColor(new java.awt.Color(0, 0, 0));

        addCategoryButton.setBackground(new java.awt.Color(255, 174, 167));
        addCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addCategoryButton.setForeground(new java.awt.Color(0, 0, 0));
        addCategoryButton.setText("Agregar categor�a");
        addCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCategoryButton.setFocusPainted(false);
        addCategoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryButtonActionPerformed(evt);
            }
        });

        deleteCategoryButton.setBackground(new java.awt.Color(255, 174, 167));
        deleteCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteCategoryButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteCategoryButton.setText("Eliminar categor�a");
        deleteCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteCategoryButton.setFocusPainted(false);
        deleteCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCategoryButtonActionPerformed(evt);
            }
        });

        addProductComboBox.setBackground(new java.awt.Color(255, 255, 255));
        addProductComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addProductComboBox.setForeground(new java.awt.Color(0, 0, 0));
        addProductComboBox.setMaximumRowCount(20);
        addProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ArrayToString.getStringArray(categoriesList)));

        addProductButton.setBackground(new java.awt.Color(255, 174, 167));
        addProductButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addProductButton.setForeground(new java.awt.Color(0, 0, 0));
        addProductButton.setText("Agregar producto");
        addProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductButton.setFocusPainted(false);
        addProductButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        editProductField.setBackground(new java.awt.Color(255, 255, 255));
        editProductField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editProductField.setForeground(new java.awt.Color(0, 0, 0));
        editProductField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        editProductField.setText("editProductField");
        editProductField.setAutoscrolls(false);
        editProductField.setCaretColor(new java.awt.Color(0, 0, 0));

        editProductButton.setBackground(new java.awt.Color(255, 174, 167));
        editProductButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editProductButton.setForeground(new java.awt.Color(0, 0, 0));
        editProductButton.setText("Editar producto");
        editProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProductButton.setFocusPainted(false);
        editProductButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductButtonActionPerformed(evt);
            }
        });

        editCategoryComboBox.setBackground(new java.awt.Color(255, 255, 255));
        editCategoryComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editCategoryComboBox.setForeground(new java.awt.Color(0, 0, 0));
        editCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ArrayToString.getStringArray(categoriesList)));

        
        deleteCategoryComboBox.setBackground(new java.awt.Color(255, 255, 255));
        deleteCategoryComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteCategoryComboBox.setForeground(new java.awt.Color(0, 0, 0));
        deleteCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ArrayToString.getStringArray(categoriesList)));

        editCategoryButton.setBackground(new java.awt.Color(255, 174, 167));
        editCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editCategoryButton.setForeground(new java.awt.Color(0, 0, 0));
        editCategoryButton.setText("Editar categor�a");
        editCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editCategoryButton.setFocusPainted(false);
        editCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addProductButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editProductButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(addCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deleteCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteCategoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteCategoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 212, 171));

        showProductListButton.setBackground(new java.awt.Color(255, 174, 167));
        showProductListButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showProductListButton.setForeground(new java.awt.Color(0, 0, 0));
        showProductListButton.setText("Ver lista de productos");
        showProductListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showProductListButton.setFocusPainted(false);
        showProductListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProductListButtonActionPerformed(evt);
            }
        });

        addUserButton.setBackground(new java.awt.Color(255, 174, 167));
        addUserButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addUserButton.setForeground(new java.awt.Color(0, 0, 0));
        addUserButton.setText("Agregar usuario");
        addUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUserButton.setFocusPainted(false);
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showProductListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(showProductListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(227, 227, 227)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
		
		// if(editUserField existe en la base de datos){
		// editUserField.getText() buscar
		// }
		dispose();
		Client client = new Client("15234156-8", "Pedro", "123123", "correo@algo.com", 949314109, null, "La Florida #153",null, null);
		ManageUser manageUser = new ManageUser(client);
		manageUser.setVisible(true);
    }                                              

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    	JOptionPane.showMessageDialog(null, "Producto creado con �xito, iD: "+2124124+" y categor�a: "+addProductComboBox.getSelectedItem());
    	
    	// AQUI CREAR NUEVO PRODUCTO
    }                               
    
    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	dispose();
    	RegisterFrame registerFrame = new RegisterFrame();
    	registerFrame.setVisible(true);
    } 

    private void editProductButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    	EditProduct editProduct = new EditProduct();
    	editProduct.setVisible(true);
    }                                                 

    private void editCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    	String category = editCategoryComboBox.getSelectedItem().toString();
    	String newCategory = JOptionPane.showInputDialog(null, "Inserte nuevo nombre", "Editar categor�a", JOptionPane.INFORMATION_MESSAGE);
    	SQLCategoryService.getSQLCategoryService().update(category, newCategory);
    	
    
    	if(!category.strip().equals("")) {
    		SystemService.getSystem().refreshCategory();
    		categoriesList = SystemService.getSystem().getCategorys();
            updateComboBoxes();
    	}
    }  
    
	private void addCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    	//categoriesList.add(addCategoryField.getText());
    	SQLCategoryService.getSQLCategoryService().create(addCategoryField.getText());
    	SystemService.getSystem().refreshCategory();
    	categoriesList = SystemService.getSystem().getCategorys();
    	updateComboBoxes();
	}         
    
    private void deleteCategoryButtonActionPerformed(ActionEvent evt) {
		// TODO add your handling code here:
    	SQLCategoryService.getSQLCategoryService().delete(deleteCategoryComboBox.getSelectedItem().toString());
    	SystemService.getSystem().refreshCategory();
    	categoriesList = SystemService.getSystem().getCategorys();
    	updateComboBoxes();
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	dispose();
    	LoginFrame lf = new LoginFrame();
    	lf.setVisible(true);
    }                                          

    private void showProductListButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	dispose();
    	ProductListFrame productListFrame = new ProductListFrame();
    	productListFrame.setVisible(true);
    }                 
    
    private void updateComboBoxes() {
    	editCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ArrayToString.getStringArray(categoriesList)));
    	deleteCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ArrayToString.getStringArray(categoriesList)));
    	addProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ArrayToString.getStringArray(categoriesList)));    	
    }

	private void updateCategoriesList(String oldName, String newName) {
		for(int i=0; i<categoriesList.size(); i++) {
			if(categoriesList.get(i).equals(oldName)) {
				categoriesList.set(i, newName);
			}
		}
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdminEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addCategoryButton;
    private javax.swing.JTextField addCategoryField;
    private javax.swing.JButton addProductButton;
    private javax.swing.JComboBox<String> addProductComboBox;
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteCategoryButton;
    private javax.swing.JComboBox<String> deleteCategoryComboBox;
    private javax.swing.JButton editCategoryButton;
    private javax.swing.JComboBox<String> editCategoryComboBox;
    private javax.swing.JButton editProductButton;
    private javax.swing.JTextField editProductField;
    private javax.swing.JButton editUserButton;
    private javax.swing.JTextField editUserField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton showProductListButton;
    private ArrayList<String> categoriesList;
    // End of variables declaration                   
}
