package Panels;
import java.awt.event.ActionEvent;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import Domain.Product;
public class MenuAdminEdit extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuAdminEdit() {
    	// SE DEBERIA PASARLE UNA LINKED LIST AL FRAME, ESTO ES EJEMPLO
    	categoriesList = new LinkedList<>();
    	categoriesList.add("Hogar");
    	categoriesList.add("Patio");
    	categoriesList.add("Tecnología");
    	categoriesList.add("Vestuario");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editUserButton = new javax.swing.JButton();
        addProductButton = new javax.swing.JButton();
        editProductButton = new javax.swing.JButton();
        addCategoryButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        addCategoryField = new javax.swing.JTextField();
        editUserField = new javax.swing.JTextField();
        editProductField = new javax.swing.JTextField();
        deleteCategoryField = new javax.swing.JTextField();
        deleteCategoryButton = new javax.swing.JButton();
        categoryComboBox = new javax.swing.JComboBox<>();
        productListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú de Administrador");
        setBackground(new java.awt.Color(255, 212, 171));
        setBounds(new java.awt.Rectangle(0, 0, 1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 212, 171));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        editUserButton.setBackground(new java.awt.Color(255, 174, 167));
        editUserButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editUserButton.setForeground(new java.awt.Color(0, 0, 0));
        editUserButton.setText("Administrar usuarios");
        editUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editUserButton.setFocusPainted(false);
        editUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        addProductButton.setBackground(new java.awt.Color(255, 174, 167));
        addProductButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addProductButton.setForeground(new java.awt.Color(0, 0, 0));
        addProductButton.setText("Agregar producto");
        addProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductButton.setFocusPainted(false);
        addProductButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        editProductButton.setBackground(new java.awt.Color(255, 174, 167));
        editProductButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editProductButton.setForeground(new java.awt.Color(0, 0, 0));
        editProductButton.setText("Editar producto");
        editProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProductButton.setFocusPainted(false);
        editProductButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductButtonActionPerformed(evt);
            }
        });

        addCategoryButton.setBackground(new java.awt.Color(255, 174, 167));
        addCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addCategoryButton.setForeground(new java.awt.Color(0, 0, 0));
        addCategoryButton.setText("Agregar categoría");
        addCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCategoryButton.setFocusPainted(false);
        addCategoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 212, 171));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setFocusPainted(false);
        backButton.setFocusable(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addCategoryField.setBackground(new java.awt.Color(255, 255, 255));
        addCategoryField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addCategoryField.setForeground(new java.awt.Color(0, 0, 0));
        addCategoryField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addCategoryField.setText("addCategoryField");
        addCategoryField.setAutoscrolls(false);
        addCategoryField.setCaretColor(new java.awt.Color(0, 0, 0));

        editUserField.setBackground(new java.awt.Color(255, 255, 255));
        editUserField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editUserField.setForeground(new java.awt.Color(0, 0, 0));
        editUserField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        editUserField.setText("editUserField");
        editUserField.setCaretColor(new java.awt.Color(0, 0, 0));

        editProductField.setBackground(new java.awt.Color(255, 255, 255));
        editProductField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editProductField.setForeground(new java.awt.Color(0, 0, 0));
        editProductField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        editProductField.setText("editProductField");
        editProductField.setAutoscrolls(false);
        editProductField.setCaretColor(new java.awt.Color(0, 0, 0));

        deleteCategoryField.setBackground(new java.awt.Color(255, 255, 255));
        deleteCategoryField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteCategoryField.setForeground(new java.awt.Color(0, 0, 0));
        deleteCategoryField.setText("deleteCategoryField");
        deleteCategoryField.setCaretColor(new java.awt.Color(0, 0, 0));
        deleteCategoryField.setCaretPosition(16);

        deleteCategoryButton.setBackground(new java.awt.Color(255, 174, 167));
        deleteCategoryButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteCategoryButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteCategoryButton.setText("Eliminar Categoría");
        deleteCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteCategoryButton.setFocusPainted(false);
        deleteCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCategoryButtonActionPerformed(evt);
            }
        });

        categoryComboBox.setBackground(new java.awt.Color(255, 255, 255));
        categoryComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        categoryComboBox.setForeground(new java.awt.Color(0, 0, 0));
        categoryComboBox.setMaximumRowCount(20);
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(getStringArray(categoriesList)));

        productListButton.setBackground(new java.awt.Color(255, 174, 167));
        productListButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productListButton.setForeground(new java.awt.Color(0, 0, 0));
        productListButton.setText("Ver Lista de Productos");
        productListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productListButton.setFocusPainted(false);
        productListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editProductButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCategoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addProductButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(editUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(productListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(373, 373, 373))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(productListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private String[] getStringArray(LinkedList<String> categoriesList2) {
		// TODO Auto-generated method stub
    	String[] array = new String[categoriesList.size()];
    	for(int i=0; i<categoriesList.size(); i++) {
    		array[i] = categoriesList.get(i);
    	}
		return array;
	}

	private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
		dispose();
		ManageUser manageUser = new ManageUser();
		manageUser.setVisible(true);
    }                                              

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    	JOptionPane.showMessageDialog(null, "Producto creado con éxito, iD: "+2124124+" y categoría: "+categoryComboBox.getSelectedItem());
    	
    	// AQUI CREAR NUEVO PRODUCTO
    	
    }                                                

    private void editProductButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    	EditProduct editProduct = new EditProduct();
    	editProduct.setVisible(true);
    	
    }                                                 

    private void addCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    	categoriesList.add(addCategoryField.getText());
    	categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(getStringArray(categoriesList)));
    }         
    
    private void deleteCategoryButtonActionPerformed(ActionEvent evt) {
		// TODO add your handling code here:
    	categoriesList.remove(deleteCategoryField.getText());
    	categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(getStringArray(categoriesList)));
	}

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	dispose();
    	LoginFrame lf = new LoginFrame();
    	lf.setVisible(true);
    }                                          

                                        

    private void productListButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	dispose();
    	ProductListFrame productListFrame = new ProductListFrame();
    	productListFrame.setVisible(true);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdminEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addCategoryButton;
    private javax.swing.JTextField addCategoryField;
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JButton deleteCategoryButton;
    private javax.swing.JTextField deleteCategoryField;
    private javax.swing.JButton editProductButton;
    private javax.swing.JTextField editProductField;
    private javax.swing.JButton editUserButton;
    private javax.swing.JTextField editUserField;
    private javax.swing.JButton productListButton;
    private javax.swing.JPanel jPanel1;
    private LinkedList<String> categoriesList;
    // End of variables declaration                   
}
